### PR TITLE
Remove the vmware_rest_client doc_fragment

### PR DESCRIPTION
**Pull request by abadger**
This doc_fragment belongs in (and is already present in) the
community.vmware repository:

https://github.com/ansible-collections/vmware/blob/master/plugins/doc_fragments/vmware_rest_client.py

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### ADDITIONAL INFORMATION
This is similar to: https://github.com/ansible-collections/vmware_rest/pull/5

It's just that it's needed for the docs_fragment in addition to the module_utils.

### CODE REVIEW

**Comment by Akasurde** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Comment by Akasurde** [comment]
recheck

**Comment by goneri** [comment]
Thanks for the patch @abadger, it was actually conflicting with my large re-factoring branch. This is the reason why I didn't apply it. The problem is now resolved.

**Pull request closed without merging**
