### PR TITLE
automagically refresh the modules

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/617

Automatically refresh the modules on the fly.

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by pabelanger** [comment]
> Depends-On: [ansible/ansible-zuul-jobs#559](https://github.com/ansible/ansible-zuul-jobs/pull/559)
> 
> Automatically refresh the modules on the fly.

I feel if this was done, it would be very difficult to audit the code over time.  Part of the reason  version control system are great, is the ability to go back in time and look at snapshots.  By moving to a process where the modules are built at runtime and not stored in git, it starts to make it more harder to trace breaks or git blame.

What are your thoughts, like we do for linters job, is to add a check if source code is always up today, but still committed into git like you have here.

**Comment by goneri** [comment]
> > Depends-On: [ansible/ansible-zuul-jobs#559](https://github.com/ansible/ansible-zuul-jobs/pull/559)
> > Automatically refresh the modules on the fly.
> 
> I feel if this was done, it would be very difficult to audit the code over time. Part of the reason version control system are great, is the ability to go back in time and look at snapshots. By moving to a process where the modules are built at runtime and not stored in git, it starts to make it more harder to trace breaks or git blame.
> 
> What are your thoughts, like we do for linters job, is to add a check if source code is always up today, but still committed into git like you have here.

Generated code in the git repository is also a source of trouble. It's hard to understand what have changed when every commit comes with 400 changed files. And a rebase become painful. This being said, it may possible to deal with that with the right `git log` and `git rebase` parameters. I'm still not sure what is the best strategy.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Pull request merged**
